### ISSUE TITLE
uiTest test helper throws time for infinitely animating widgets

### ISSUE THREAD

**Issue by aeruhxi** [AcmeSoftwareLLC/clean_framework#31]
## Problem
uiTest relies on `pumpAndSettle` internally, which never settles for an infinitely animating widget like `CircularProgressIndicator`, and throws after a timeout.

## Possible Solution
Allow an option to use `pump` with a particular duration in `uiTest`.

**Comment by sarbagyastha** [comment]
Thanks for reporting the issue. Yes, the `pumpAndSettle` shouldn't have been done internally.
