### ISSUE TITLE
Documentation not clear "We have to main components

### ISSUE THREAD

**Issue by cyeh1234** [AcmeSoftwareLLC/clean_framework#39]
Documentation not clear "We have to main components

![image](https://user-images.githubusercontent.com/5484253/148252379-1017928c-0a5d-4b94-8fa6-e05c14c9083c.png)

**Comment by cyeh1234** [comment]
Probably meant:
We have **two** main components

Diagram has another component: Controller

**Comment by cyeh1234** [comment]
![image](https://user-images.githubusercontent.com/5484253/148253987-b191f625-20a7-4ffb-814f-6af6811fb8e1.png)
Probably meant:
which contain data and behavior

**Comment by sarbagya-acme** [comment]
Thank you for reporting. This has been fixed.
