### ISSUE TITLE
You should be using a full-function Either from fpdart, not the weak limited one you have

### ISSUE THREAD

**Issue by RandalSchwartz** [AcmeSoftwareLLC/clean_framework#95]
Noticed you're not using fpdart's Either.  It has more rigor, is better documented, and has a lot more functionality than the choice you've made for a package.  I could try to construct a PR if you're interested...

**Comment by sarbagya-acme** [comment]
@RandalSchwartz Thanks for the suggestion. 

Our usage of `Either` is quite limited so we recently opted for own implementation rather than depending on other package. https://github.com/MattHamburger/clean_framework/pull/94
